name: ci

on: [push, pull_request, release]

jobs:
  test:
    runs-on: ubuntu-latest

    # Skip commits that includes "ci skip"
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: cotton_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: cotton_test
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Install deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.0.0

      - name: Check formatting
        run: deno fmt --check

      - name: Run tests
        env:
          SQLITE_DATABASE: ./db.sqlite3
          POSTGRES_DATABASE: cotton_test
          POSTGRES_HOSTNAME: localhost
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: test
          POSTGRES_USERNAME: test
          MYSQL_DATABASE: cotton_test
          MYSQL_HOSTNAME: localhost
          MYSQL_PORT: 3306
          MYSQL_USERNAME: root
        run: deno test --allow-read --allow-write --allow-net --allow-env -c tsconfig.json test.ts
