name: ci

on: [push, pull_request, release]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: cotton_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: Install deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.0.0

      - name: Check formatting
        run: deno fmt --check

      - name: Run tests
        env:
          SQLITE_DATABASE: ./db.sqlite3
          POSTGRES_DATABASE: cotton_test
          POSTGRES_HOSTNAME: postgres
          POSTGRES_PORT: 5432
          POSTGRES_PASSWORD: test
          POSTGRES_USERNAME: test
        run: deno test --allow-read --allow-net --allow-env test.ts
